### PR TITLE
Added TracerAutoConfiguration

### PR DESCRIPTION
**Pull request by whiskeysierra**
- [x] still missing some documentation

### CODE REVIEW

**Comment by whiskeysierra** [comment]
- [ ] add duplicate finder plugin to parent pom
- [ ] cleanup additional hamcrest libraries

**Comment by whiskeysierra** [comment]
@matosf I updated the versions

**Comment by whiskeysierra** [comment]
Mmh, not sure what exactly the problem is:

```
[ERROR]   The project org.zalando:tracer-spring-boot-starter:[unknown-version] (/home/travis/build/zalando/tracer/tracer-spring-boot-starter/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not transfer artifact org.zalando:tracer-parent:pom:0.2.0-SNAPSHOT from/to codehaus-snapshots (https://nexus.codehaus.org/snapshots/): nexus.codehaus.org and 'parent.relativePath' points at wrong local POM @ line 7, column 13: Unknown host nexus.codehaus.org -> [Help 2]
```

Codehaus is dead (for a while now), but travis seems to use it still, see https://github.com/travis-ci/travis-ci/issues/4629

**Comment by lukasniemeier-zalando** [comment]
Do we actually need the version bump?

**Comment by matosf** [comment]
Not really, it was just to make it up to date. It will be overriden by the
versions in our pom anyway. If this is causing the issue leave as it was.
Em 15/02/2016 6:57 da tarde, "lukasniemeier-zalando" <
notifications@github.com> escreveu:

**Comment by lukasniemeier-zalando** [comment]
@whiskeysierra rollback the version for now and merge?

**Comment by whiskeysierra** [comment]
I can try but I'm pretty sure it won't fix the problem with Travis.

**Comment by matosf** [comment]
The error in TravisCI is:
```
[ERROR]   The project org.zalando:tracer-spring-boot-starter:[unknown-version] (/home/travis/build/zalando/tracer/tracer-spring-boot-starter/pom.xml) has 1 error
[ERROR]     Non-resolvable parent POM: Could not transfer artifact org.zalando:tracer-parent:pom:0.2.0-SNAPSHOT from/to codehaus-snapshots (https://nexus.codehaus.org/snapshots/): nexus.codehaus.org and 'parent.relativePath' points at wrong local POM @ line 7, column 13: Unknown host nexus.codehaus.org -> [Help 2]
```

So maybe the solution is just adding the following to the parent element of each module, so it does not try to download the parent jar:
```
<relativePath>../pom.xml</relativePath>
```

I not 100% sure this will work because I cannot reproduce the issue, tried with maven 3.3 and maven 3.0.5, after cleaning the local repo, and always worked... so, maybe just try it. :)

**Comment by whiskeysierra** [comment]
I think it works locally because we're all using an internal mirror. Have
you tried with an empty settings.xml?

**Comment by jhorstmann** [comment]
<relativePath>../pom.xml</relativePath>

That should actually be the default if no `relativePath` is specified, I think the problem is that the version in that pom is already 0.3.0-SNAPSHOT, which is different from the specified parent version, that causes maven to look up the artifact in a repository. If the versions matched it should not have to look at a remote repository.

**Comment by matosf** [comment]
@jhorstmann 
All the modules in this branch have the same parent declaration, that is the same version in the parent pom:
```
    <parent>
        <groupId>org.zalando</groupId>
        <artifactId>tracer-parent</artifactId>
        <version>0.2.0-SNAPSHOT</version>
    </parent>
```

@whiskeysierra 
tried without settings.xml and clean repo and still not able to reproduce it, always works (using maven 3.0.5 and maven 3.3.3). :|

**Comment by matosf** [comment]
Just came to mind, maybe the problem is in the settings.xml of TravisCI, that has this old repo configured there? Anyway to check this?

**Comment by jhorstmann** [comment]
The issue is that travis is actually trying to build the merge result, in which the parent version is already 0.3.0-SNAPSHOT. It should be possible to solve the compilation problem by just incrementing the version of tracer-spring-boot-starter also to 0.3.0-SNAPSHOT.

**Comment by whiskeysierra** [comment]
This might be our problem travis-ci/travis-ci#4629, basically what @matosf said.

**Comment by whiskeysierra** [comment]
Ok, so I added the fix that is described in the travis issue and bumped the version to 0.3.0-SNAPSHOT

**Comment by jhorstmann** [comment]
Is that hack in `.travis.yml` still needed now that all modules have the same version?

**Pull request merged**
