### PR TITLE
Expose flow as header on servlet response

### PR DESCRIPTION
**Pull request by lukasniemeier-zalando**
## Description

Expose flow (id) as `x-flow-id` header in servlet response.

## Motivation and Context

* aligning response header with propagation matrix of https://github.com/zalando/tracer#usage
* ensuring backwards compatibility (tracing based on `x-flow-id` header)

## Types of changes
- [ ] Bug fix (non-breaking change which fixes an issue)
- [x] New feature (non-breaking change which adds functionality)
- [ ] Breaking change (fix or feature that would cause existing functionality to change)

## Checklist:
- [ ] My change requires a change to the documentation.
- [ ] I have updated the documentation accordingly.
- [x] I have added tests to cover my changes.

### CODE REVIEW

**Comment by whiskeysierra** [comment]
Shouldn't this be dependent on whether we received a flow id to begin with?

**Comment by lukasniemeier-zalando** [comment]
I was following the matrix of https://github.com/zalando/tracer#usage, but now I see that Riptide has an option to enable/disable by client.

Someone sending a flow id sounds like a good heuristic to detect a "legacy" client.

**Comment by whiskeysierra** [comment]
:+1:

**Comment by lukasniemeier-zalando** [comment]
:+1:

**Pull request merged**
